<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    
    <PropertyGroup>
        <PackageVersion>1.2.1</PackageVersion>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>up in blue GmbH</Authors>
        <Company>up in blue GmbH</Company>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <RepositoryUrl>https://github.com/upinblue/ScanMeX</RepositoryUrl>
        <PackageProjectUrl>https://www.naps2.com/sdk</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
        <None Include="LICENSE" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
