<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8;net462</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <RootNamespace>NAPS2.Portable</RootNamespace>
    <AssemblyName>NAPS2.Portable</AssemblyName>
    <ApplicationIcon>../NAPS2.Lib/Icons/favicon.ico</ApplicationIcon>

    <Title>ScanMe</Title>
    <Product>ScanMe</Product>
  </PropertyGroup>
  
  <Import Project="..\NAPS2.Setup\targets\CommonTargets.targets" />
  
</Project>